# Simplify your life with Statistics and NumPy


### Five functions that are a must for Data Science, Statistics and your Daily Life...

Statistics is fundamental dicipline and form of mathematical analysis that uses quantified models, representations, and synopses for a given set of real-life or experimental data. 

In other works, statistics studies methodologies to gather information, review it, analize it, and finally get conclusions aout of it.

In this Notebook five NumPy useful functions will be discused:

- Generate Random Integer Data with `np.random.randint()`
- Ordering the data with `np.sort()`
- Calculate the Mean of the data with `np.mean()`
- Calculate the Median of the data with `np.median()`
- Calculate the Standard Deviation of the data with `np.std()`

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks, or you can run it in your prefered Cloud Server.

Also, you can clone this notebook to run it localy, by clicking the "clone" button at the top of this page.

Let's start by importing numpy

In [1]:
import numpy as np

To make this excersice simpler, let us assume you are a teacher and you have 100 students. Also, you have their final marks by the end of the scholar year, which are listed in scale from 0 to 10, where 0 is bad performance and 10 is excelent performance.

You can come up with the grades if you feel like, but let's use numpy build in functions to generate our data.

The function `np.random.randint()` is a build in funciton that generate random integer numbers. It requires certain arguments or inputs which are:

1.   The lowest number, in this case 0
2.   The highst number, in this case 10
3.   Number of samples, in this case 100

And the last thing to do is to assign those values to a variable, in this case `grades`.

## Genarating Random Integer Numbers with `np.random.randint()`

It is easy to generate random data with numpy. It includes several methods to do it, depending on your data naeeds.

In this case we will focus on generate random integer data with the method `np.random.randint()`, which returns random integers from low (inclusive) to high (exclusive).

The way this method generates the random integers is  from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

You can read more about *`np.random.randint* [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html).

Now all you have to do is to assigne the returned value of `np.random.randint()`, as follows:

In [15]:
# This is how you can calculate the mean of an array 
grades = np.random.randint(0, 101, 100)
grades

array([ 79,  96,  82,  54,  71,  55,  71,  63,  50,  12,  90,  98,  76,
        86,  44,  31,   0,  50,  24,  59,  27,  42,  11,  40,  90,  66,
        29,  46,  72,   6,  64,  59,  79,   8,  31,   1,  70,  37,  77,
        58,  46,  92,  30,  69,  63,  86,  56,  53,  29,  37,  11,   8,
        68,  37,  35,  95,  10,  74,  80,   0,  16,  61,  32,  56,  59,
        53,  29,  26, 100,  30,   7,  97,  28,  94,   7,  26,  59,  75,
        79,  33,  66,  54,  79,  71,  20,  95,   2,  33,  79,   6,  16,
        74,  20,   0,  63,  52,  21,  40,  75,  54])

You can check what type is the variable `grades` as follows:

In [16]:
type(grades)

numpy.ndarray

We can see that `grades` is type `numpy.ndarray`. 

To check the size, run the following command:

In [17]:
grades.size

100

And finally, to check the shape, run the following cell.

In [18]:
grades.shape

(100,)

It is possible to generate matrices or arrays of different sizes with this method by changing the paramenter `size`,  which by default is set to `None`:

In [33]:
# This explains another way to generate data with np.random.randint()
matrix = np.random.randint(0, 11, size=(10,10))
matrix

array([[ 5,  1,  5,  7,  6, 10,  0,  2,  1,  5],
       [ 2,  6,  3,  6,  6,  5,  4,  0,  7,  4],
       [ 2,  3,  7,  9,  4,  1, 10, 10,  1,  6],
       [ 2,  8, 10,  6,  8,  3,  4,  2,  3,  1],
       [ 5,  6, 10,  4,  1,  7,  3,  9,  2,  3],
       [ 4,  9,  9,  1,  3,  3,  4,  7, 10, 10],
       [ 2,  4,  5,  6,  9,  6,  7,  9, 10, 10],
       [ 9,  9,  8,  1,  0,  3,  6, 10,  9, 10],
       [ 1,  6,  1,  9,  2,  6,  6,  1, 10,  4],
       [ 2,  1,  5,  9,  0,  8,  5,  7,  5,  3]])

There are several arguments that can be used in `np.random.randint`. The most common mistake by using this method is to input a non valid argument. 

For example use a tuple in the first argument thinking that will be the range of the generated numbers. Lets say genrate random data from 0 to 10 and we input this `(0, 10)` as first argument:

In [21]:
# This illustrates how to break 
np.random.randint((0, 10), 20, (4,5,2,5))

ValueError: ignored

The reason, why it breaks is because you will need to insert float or integer values in the first 2 arguments.

We all know that you are a very responsible and organized teacher. This is why you decide to extract some information from your students marks to see how they did during the scholar year, and of course to see if you can improve something in the feature. 

Lets start to talk about some statistical terms like *sorting data*, *mean*, *median*, and *standard deviation*.

## Ordering the data with `np.sort()`

In statistics the visualization of the data is very important. One can easily see a lot of valuable information just by ordering the data. 

Numpy has a method called `np.sort()`, which returns a sorted copy of an array. For more about how to use this method click [here](https://numpy.org/doc/stable/reference/generated/numpy.sort.html?highlight=sort).

To sort the `grades` in this work, you will just have to pass the array into the method `np.sort()`, as follows:

In [37]:
# This shows how to use the method 
sorted_grades = np.sort(grades)
sorted_grades

array([  0,   0,   0,   1,   2,   6,   6,   7,   7,   8,   8,  10,  11,
        11,  12,  16,  16,  20,  20,  21,  24,  26,  26,  27,  28,  29,
        29,  29,  30,  30,  31,  31,  32,  33,  33,  35,  37,  37,  37,
        40,  40,  42,  44,  46,  46,  50,  50,  52,  53,  53,  54,  54,
        54,  55,  56,  56,  58,  59,  59,  59,  59,  61,  63,  63,  63,
        64,  66,  66,  68,  69,  70,  71,  71,  71,  72,  74,  74,  75,
        75,  76,  77,  79,  79,  79,  79,  79,  80,  82,  86,  86,  90,
        90,  92,  94,  95,  95,  96,  97,  98, 100])

this method has different algortithms implemented inside to order the data. By defualt this method uses the so called "quicksort" algorithm, but you can change the algorithm used with the argument `kind`, where the possible inputs are: `{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}`

In [41]:
np.sort(grades, kind='stable')

array([  0,   0,   0,   1,   2,   6,   6,   7,   7,   8,   8,  10,  11,
        11,  12,  16,  16,  20,  20,  21,  24,  26,  26,  27,  28,  29,
        29,  29,  30,  30,  31,  31,  32,  33,  33,  35,  37,  37,  37,
        40,  40,  42,  44,  46,  46,  50,  50,  52,  53,  53,  54,  54,
        54,  55,  56,  56,  58,  59,  59,  59,  59,  61,  63,  63,  63,
        64,  66,  66,  68,  69,  70,  71,  71,  71,  72,  74,  74,  75,
        75,  76,  77,  79,  79,  79,  79,  79,  80,  82,  86,  86,  90,
        90,  92,  94,  95,  95,  96,  97,  98, 100])

Also, if you had a bigger array you will be able to specify which axis of the array you would like to sort. In this case the `grades` array is a 1D array, for instance if you change the argument `axis` from its defualt value `1` to `2` you will get an error like the following one:

In [46]:
np.sort(grades, axis=2)

AxisError: ignored

So now you have it! You sorted the marks of your students in an ascending way, and now we can give it a nice print:

In [47]:
print("The sorted grades of the students \n", sorted_grades)

The sorted grades of the students 
 [  0   0   0   1   2   6   6   7   7   8   8  10  11  11  12  16  16  20
  20  21  24  26  26  27  28  29  29  29  30  30  31  31  32  33  33  35
  37  37  37  40  40  42  44  46  46  50  50  52  53  53  54  54  54  55
  56  56  58  59  59  59  59  61  63  63  63  64  66  66  68  69  70  71
  71  71  72  74  74  75  75  76  77  79  79  79  79  79  80  82  86  86
  90  90  92  94  95  95  96  97  98 100]


## Mean or `np.mean()`

There are several kinds of *mean* in mathematics, but for a data set like the one used in this case, the *mean* is nothing but the *average* of the data set. In other words, the sum of values insede the data set (`grades`) devided by the number of values in the data set (there are `100` values inside `grades`).

You can read more about *mean* [here](https://en.wikipedia.org/wiki/Mean).

Fortunately for us, **NumPy** has its own implementation of mean and you will not have to worry about make the calculation. 

To calculate the *mean* of a data set, you will have to use the method `np.mean()`, which returns the average of the array elements in this case `grades`. The average is taken over the flattened array by default. For more about how to use this method click [here](https://numpy.org/doc/stable/reference/generated/numpy.mean.html?highlight=mean#numpy.mean).

Now all you have to do is to assigne the returned value of `np.mean(grades)`, as follows:

In [22]:
# This is how you can calculate the mean of an array 
mean = np.mean(grades)
mean

49.7

As it was mentioned above, `np.mean()` calculated the sum of all the elements inside the array and devide the sum by the total number of elements inside the array. 

So, what happens inside this method is listed as follows:

In [23]:
# This explains how np.mean() works
sum = 0
for i in grades:
  sum += i

mean_explaned = sum / len(grades)
mean_explaned

49.7

There are several arguments that can be used in `np.mean`. In most cases you will not need to change the defualts, but if you have a bigger array, lets say a matrix, you can change the `axis=` argument and select which axis of the array you want to calculate.

In our case since the `grades` array is a 1D array (`(100,)`) the defualt value for `axis=0` will work, but if you change it, the following will happen:

In [24]:
# This illustrates how to break np.mean()
mean = np.mean(grades, axis=1)

IndexError: ignored

The reason why it broke is because the array was declared as a 1D horizontal array, for instance `axis=0` will be the horizontal axis. If you change the argument `axis=1`, it will perform the calculation in the second dimension of the array, which in this case does not exist.

So now you have it! You calculated the *mean* mark of your students during the scholar year, and now we can give it a nice print:

In [25]:
print("The mean or average mark of the students is: ", mean)

The mean or average mark of the students is:  49.7


## Median or `np.median()`

The *median* is the middle number in a sorted, ascending or descending list of numbers and it can be summarized in 2 escenarios:

* If there is an odd amount of numbers, the median value is the number that is in the middle, with the same amount of numbers below and above.
* If there is an even amount of numbers in the list, the middle pair must be determined, added together, and divided by two to find the median value.

You can read more about the *median* [here](https://www.investopedia.com/terms/m/median.asp#:~:text=Key%20Takeaways-,The%20median%20is%20the%20middle%20number%20in%20a%20sorted%2C%20ascending,the%20average%20of%20the%20values.).

**NumPy** has its own implementation of median.

To calculate the *median* of a data set, you will have to use the method `np.median()`, which compute the median along the specified axis and returns the median of the array elements, in this case `grades`. For more about how to use this method click [here](https://numpy.org/doc/stable/reference/generated/numpy.median.html?highlight=median#numpy.median).

Now all you have to do is to assigne the returned value of `np.median(grades)`, as follows:

In [35]:
# This is how you can calculate the mean of an array 
median = np.median(grades)
median

53.5

As it was mentioned above, `np.median()` calculated the middle element inside the array. 

So, what happens inside this method is that `np.median()` sorted the array `grades` in ascending order and picked the element which was right in the middle, as in the following example.

By using `np.sort()` you can order the grades in ascending order and look ar the output.

In [70]:
# This explains how np.median() works
np.sort(grades)

array([50, 51, 51, 52, 52, 53, 53, 53, 54, 54, 54, 55, 55, 56, 56, 57, 57,
       58, 59, 59, 60, 60, 60, 60, 60, 60, 61, 61, 62, 62, 62, 62, 62, 63,
       63, 64, 65, 66, 66, 67, 67, 67, 68, 69, 69, 70, 71, 72, 72, 73, 73,
       74, 74, 74, 74, 75, 76, 76, 77, 77, 79, 80, 80, 80, 80, 82, 83, 83,
       83, 84, 85, 85, 85, 86, 86, 86, 86, 87, 87, 87, 87, 88, 88, 88, 89,
       90, 90, 92, 93, 95, 95, 96, 96, 97, 97, 98, 98, 98, 99, 99])

There are several arguments that can be used in `np.median()`. In most cases you will not need to change the defualts, but if you have a bigger array, lets say a matrix, you can change the `axis=` argument and select which axis of the array you want to calculate.

In our case since the `grades` array is a 1D array (`(100,)`) the defualt value for `axis=0` will work, but if you change it, the following will happen:

In [57]:
# This illustrates how to break np.median()
median = np.median(grades, axis=1)

AxisError: ignored

The reason why it broke is because the array was declared as a 1D horizontal array, for instance `axis=0` will be the horizontal axis. If you change the argument `axis=1`, it will perform the calculation in the second dimension of the array, which in this case does not exist.

So now you have it! You calculated the *median* mark of your students during the scholar year, and now we can give it a nice print:

In [55]:
print("The median mark of the students is: ", median)

The median mark of the students is:  53.5


## Standard Deviation or `np.std()`

The *standard diviation* is a measure of the amount of variation or dispersion of a set of values, where 

* A low value indicates that the values tend to be close to the mean (or the spected value) of the data set.
* A high value indicates that the values of the data set are spread out over a wider range.

You can read more about the *standard diviation* [here](https://en.wikipedia.org/wiki/Standard_deviation).

**NumPy** has its own implementation of standard diviation.

To calculate the *standard diviation* of a data set, you will have to use the method `np.std()`, which compute the standard deviation and returns the standard deviation, a measure of the spread of a distribution, of the array elements. The standard deviation is computed for the flattened array by default, in this case `grades`. For more about how to use this method click [here](https://numpy.org/doc/stable/reference/generated/numpy.std.html?highlight=numpy%20std#numpy.std).

Now all you have to do is to assigne the returned value of `np.std(grades)`, as follows:

In [56]:
# This is how you can calculate the mean of an array 
standard_deviation = np.std(grades)
standard_deviation

28.173569173961614

As it was mentioned before the *standard deviation* measures the variation or dispersion in the data set. 

The next block breaks the steps to calculate it:

In [93]:
# This explains how np.std() works

# First we need to calculate the mean or average as before
sum = 0
for i in grades:
  sum += i

mean_explaned = sum / len(grades)

# Then calcualte the numerator of the division 
numerator_up = 0
for i in grades:
  numerator_up += (i - mean_explaned)**2

# Improt math to calculate the square root
import math
# calculate the standard diviation of the data set
math.sqrt(numerator_up / len(grades))

14.455794685869057

There are several arguments that can be used in `np.std()`. In most cases you will not need to change the defualts, but if you have a bigger array, lets say a matrix, you can change the `axis=` argument and select which axis of the array you want to calculate.

In our case since the `grades` array is a 1D array (`(100,)`) the defualt value for `axis=0` will work, but if you change it, the following will happen:

In [91]:
# This illustrates how to break np.std()
standard_deviation = np.std(grades, axis=1)

IndexError: ignored

The reason why it broke is because the array was declared as a 1D horizontal array, for instance `axis=0` will be the horizontal axis. If you change the argument `axis=1`, it will perform the calculation in the second dimension of the array, which in this case does not exist.

So now you have it! You calculated the *standard deviation* of your students marks during the scholar year, and now we can give it a nice print:

In [57]:
print("The standard deviation of the students marks is: ", standard_deviation)

The standard deviation of the students marks is:  28.173569173961614


## Conclusion

Well, as you can see just with a few lines of code you can get a lot of information from a simple data set. Let us summarize what we have obtained. 

1. Random integer data
2. Sorted the random data in ascending order
3. Calculated the mean of the data set
4. Calculated the meadian of the data set 
5. Calculated the stardat deviation of the data set

You can feel proud of being a responsible teacher and you might like to share this information with your coworkers and/or your students' parents.

## Commit to Jovian.ml



In [ ]:
!pip install jovian --upgrade -q
import jovian
jovian.commit(project='assignment-02-numpy-array-operations')

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:

* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Statistics - Investopedia : https://www.investopedia.com/terms/s/statistics.asp#:~:text=Statistics%20is%20a%20form%20of,Mean 
* Statistics - Wikipedia : https://en.wikipedia.org/wiki/Statistics 
* The arithmetic mean : https://en.wikipedia.org/wiki/Arithmetic_mean
* What is the median? : https://www.investopedia.com/terms/m/median.asp#:~:text=Key%20Takeaways-,The%20median%20is%20the%20middle%20number%20in%20a%20sorted%2C%20ascending,the%20average%20of%20the%20values. 
* Standart Deviation : https://en.wikipedia.org/wiki/Standard_deviation

In [ ]:
jovian.commit()